services:
  planner:
    build:
      context: .
      dockerfile: planner/Dockerfile
    container_name: planner
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      config-init:
        condition: service_completed_successfully
      minio-init:
        condition: service_started
    volumes:
      - planner-data:/var/lib/task-manager
      - config-data:/etc/task-manager/planner
      - ./testdata:/app/testdata

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      config-init:
        condition: service_completed_successfully
      minio-init:
        condition: service_started
    command: ["worker", "-config", "/etc/task-manager/worker/config.json"]
    volumes:
      - config-data:/etc/task-manager/worker

  config-init:
    image: bhgedigital/envsubst
    container_name: config-init
    volumes:
      - ./config.template.json:/template.json:ro
      - config-data:/output
    environment:
      KAFKA_PORT:            ${KAFKA_PORT}
      KAFKA_TASK_TOPIC:      ${KAFKA_TASK_TOPIC}
      KAFKA_RESULT_TOPIC:    ${KAFKA_RESULT_TOPIC}
      MINIO_PORT:            ${MINIO_PORT}
      MINIO_ROOT_USER:       ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD:   ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_REGION:          ${MINIO_REGION}
    command: sh -c "envsubst < /template.json > /output/config.json"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT:                zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS:             PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:${KAFKA_PORT}", "--list" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-init:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP:    kafka:${KAFKA_PORT}
      KAFKA_TASK_TOPIC:   ${KAFKA_TASK_TOPIC}
      KAFKA_RESULT_TOPIC: ${KAFKA_RESULT_TOPIC}
    volumes:
      - ./scripts/kafka-create-topics.sh:/init.sh:ro
    entrypoint: ["bash", "/init.sh"]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT}"
    depends_on:
      - kafka
    environment:
      SERVER_PORT:                       ${KAFKA_UI_PORT}
      AUTH_TYPE:                         DISABLED
      KAFKA_CLUSTERS_0_NAME:             local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${KAFKA_PORT}

  sqlite-web:
    image: ghcr.io/coleifer/sqlite-web:latest
    container_name: sqlite-web
    depends_on:
      - planner
    ports:
      - "${SQLITE_WEB_PORT}:${SQLITE_WEB_PORT}"
    command: [ "-H", "0.0.0.0", "-p", "${SQLITE_WEB_PORT}", "/data/planner.db" ]
    entrypoint: [ "sqlite_web" ]
    volumes:
      - planner-data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_UI_PORT}:${MINIO_UI_PORT}"
    environment:
      MINIO_ROOT_USER:       ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD:   ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_REGION:          ${MINIO_REGION}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 3s
    command: server /data --console-address ":${MINIO_UI_PORT}"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    volumes:
      - ./scripts/minio-create-bucket.sh:/init.sh:ro
    entrypoint: sh /init.sh

volumes:
  planner-data:
  config-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  minio-data:
